### ISSUE TITLE
The init isolate encountered an error Invalid argument(s): Failed to lookup symbol 'stockfish_init

### ISSUE THREAD

**Issue by SchulzKilian** [ArjanAswal/Stockfish#17]
That is the error I get, whenever I try to simply initialize stockfish in my application.
After initializing in the MyApp class, I then tried to play around with variations of the following:
```
waitUntilReady();
    stockfish.stdin = 'isready';
    stockfish.stdin = 'go movetime 3000';
    stockfish.stdin = 'go infinite';
    stockfish.stdin = 'stop';
    waitUntilReady();
    stockfish.stdout.listen(
      (event) => print(event),
    );
```
Similar issue with the example code from the documentation:
`
Bad state: Stockfish is not ready (StockfishState.error)`

**Comment by daohoangson** [comment]
`Failed to lookup symbol 'stockfish_init'` appears to be an issue with Dart ffi. What is your dev environment? `flutter doctor -v` output would be useful.

**Comment by SchulzKilian** [comment]
> 

yes, it actually was. Thanks for the idea , it now works perfectly
