### ISSUE TITLE
Any way to reduce this package size?

### ISSUE THREAD

**Issue by leonfresh** [ArjanAswal/Stockfish#35]
Works great but the size is too large? Is there any way to make it smaller?

It single handedly makes my app 180 mb for the app bundle. 

I saw that max app bundle size is 100mb, so I cant release to app store?

![image](https://github.com/ArjanAswal/Stockfish/assets/10756588/3f578068-f139-429f-b3bd-41df1af84459)

**Comment by daohoangson** [comment]
The app bundle size grows significantly because it is built for all architectures. Google Play Store will prepare separate download for each device so the actual size will grow only ~30MB. Most of this is the `.so` file which is compiled directly from source so it's hard to optimize further.

**Comment by leonfresh** [comment]
> The app bundle size grows significantly because it is built for all architectures. Google Play Store will prepare separate download for each device so the actual size will grow only ~30MB. Most of this is the `.so` file which is compiled directly from source so it's hard to optimize further.

I see thank you. It ended up being 40mb which is okay for now
