### ISSUE TITLE
Error in certain positions: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x6f8b0bc000 in tid 2074 (DartWorker), pid 1920 (app_name)

### ISSUE THREAD

**Issue by Mercutio1243** [ArjanAswal/Stockfish#37]
**EDIT2:**
Error was with the fen position itself, which led to the Stockfish chess engine to crash. So, please feel free to close the issue here. 

At least for users of this package it could be an interesting insight that a fatal signal 11 error can result from the core Stockfish chess engine crashing.

**EDIT:**
Also the official Stockfish 15.1 Windows x64 exe crashes with this position. I have therefore opened an issue directly with the Stockfish engine here: https://github.com/official-stockfish/Stockfish/issues/5071

**Original post:**
In my small chess app, I get the following error in rare occasions. The error will deterministically occur in my app for the position below. It keeps occurring after reinstalling app and restarting device. The app runs in debug mode. 

Any indications at all on why this might be happening and why it keeps occurring for me in these specific positions.

```
Stockfish is ready.
Stockfish stdin: position fen 3qk1nb/1p3p2/p1r1p1p1/3p4/3P4/2N1BP2/PPPQ1P2/R3K3 w Qk - 0 15
Stockfish stdin: go movetime 3000
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/t2quew/t2q:14/UP1A.231005.007/G996U1UESAFXAB:user/release-keys'
Revision: '13'
ABI: 'arm64'
Processor: '6'
Timestamp: 2024-02-24 17:25:49.265661073+0100
Process uptime: 27s
Cmdline: com.cbt.chess_blunder_trainer
pid: 1920, tid: 2074, name: DartWorker  >>> com.cbt.chess_blunder_trainer <<<
uid: 10526
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x0000006f8b0bc000
    x0  000000702b2f9e08  x1  0000000000000000  x2  0000000000000000  x3  0000006f8f72f820
    x4  0000000000000020  x5  0000000040100401  x6  000000000000000e  x7  b40000708554fac0
    x8  0000000000000010  x9  0000000000202963  x10 0000000000000038  x11 000000000000000c
    x12 b400006f8b0bc000  x13 0000000000000000  x14 0000006f8f650b08  x15 b400006f8a8b1a78
    x16 0000006f8f62f308  x17 0000006f8f5cbb9c  x18 000000702a80a000  x19 0000000000000006
    x20 0000000000000002  x21 b400006f8a8b1a70  x22 0000000000000038  x23 0000000000000005
    x24 0000000000000003  x25 0000006f8f650b08  x26 000000000000000a  x27 000000000000000c
    x28 0000000000000004  x29 000000702b2f9f30
    lr  0000006f8f5941b4  sp  000000702b2f9de0  pc  0000006f8f59424c  pst 0000000080001000
7 total frames
backtrace:
      #00 pc 0000000002d6c24c  /data/app/~~dXfyDasKRmvqw-s_ny-r9w==/com.cbt.chess_blunder_trainer-X0a1XdmjSzGChB-ZKotDcA==/base.apk!libstockfish.so (offset 0x407f000) (Stockfish::Position::set(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, bool, Stockfish::StateInfo*, Stockfish::Thread*)+1012) (BuildId: 7b73f3d0201387c3449a2e644f7cd60fa1bafa62)
      #01 pc 0000000002d8ad4c  /data/app/~~dXfyDasKRmvqw-s_ny-r9w==/com.cbt.chess_blunder_trainer-X0a1XdmjSzGChB-ZKotDcA==/base.apk!libstockfish.so (offset 0x407f000) (Stockfish::ThreadPool::start_thinking(Stockfish::Position&, std::__ndk1::unique_ptr<std::__ndk1::deque<Stockfish::StateInfo, std::__ndk1::allocator<Stockfish::StateInfo> >, std::__ndk1::default_delete<std::__ndk1::deque<Stockfish::StateInfo, std::__ndk1::allocator<Stockfish::StateInfo> > > >&, Stockfish::Search::LimitsType const&, bool)+880) (BuildId: 7b73f3d0201387c3449a2e644f7cd60fa1bafa62)
      #02 pc 0000000002d902f8  /data/app/~~dXfyDasKRmvqw-s_ny-r9w==/com.cbt.chess_blunder_trainer-X0a1XdmjSzGChB-ZKotDcA==/base.apk!libstockfish.so (offset 0x407f000) (BuildId: 7b73f3d0201387c3449a2e644f7cd60fa1bafa62)
      #03 pc 0000000002d8e940  /data/app/~~dXfyDasKRmvqw-s_ny-r9w==/com.cbt.chess_blunder_trainer-X0a1XdmjSzGChB-ZKotDcA==/base.apk!libstockfish.so (offset 0x407f000) (Stockfish::UCI::loop(int, char**)+2572) (BuildId: 7b73f3d0201387c3449a2e644f7cd60fa1bafa62)
      #04 pc 0000000002d609b0  /data/app/~~dXfyDasKRmvqw-s_ny-r9w==/com.cbt.chess_blunder_trainer-X0a1XdmjSzGChB-ZKotDcA==/base.apk!libstockfish.so (offset 0x407f000) (main+444) (BuildId: 7b73f3d0201387c3449a2e644f7cd60fa1bafa62)
      #05 pc 0000000002d4ea30  /data/app/~~dXfyDasKRmvqw-s_ny-r9w==/com.cbt.chess_blunder_trainer-X0a1XdmjSzGChB-ZKotDcA==/base.apk!libstockfish.so (offset 0x407f000) (stockfish_main+68) (BuildId: 7b73f3d0201387c3449a2e644f7cd60fa1bafa62)
      #06 pc 0000000000007bc4  [anon:dart-code]
Lost connection to device.

Exited.
```

The position is from the following game:
> [Event "Live Chess"]
> [Site "Chess.com"]
> [Date "2024.02.17"]
> [Round "-"]
> [White "only_strong_moves"]
> [Black "Hikaru"]
> [Result "0-1"]
> [CurrentPosition "3q4/1p1k1p2/p3p1p1/1n1pP3/8/1P3PN1/P1rQKP2/7R w - -"]
> [Timezone "UTC"]
> [ECO "A00"]
> [ECOUrl "https://www.chess.com/openings/Van-Geet-Opening-Myers-Attack"]
> [UTCDate "2024.02.17"]
> [UTCTime "19:05:42"]
> [WhiteElo "2699"]
> [BlackElo "3282"]
> [TimeControl "180"]
> [Termination "Hikaru won by resignation"]
> [StartTime "19:05:42"]
> [EndDate "2024.02.17"]
> [EndTime "19:07:16"]
> [Link "https://www.chess.com/game/live/101935573871"]
> 
> 1. Nc3 {[%clk 0:03:00]} 1... g6 {[%clk 0:03:00]} 2. h4 {[%clk 0:02:59.6]} 2... Bg7 {[%clk 0:02:59.9]} 3. h5 {[%clk 0:02:59.2]} 3... d5 {[%clk 0:02:59.8]} 4. hxg6 {[%clk 0:02:58.4]} 4... hxg6 {[%clk 0:02:57.5]} 5. Rxh8 {[%clk 0:02:58.3]} 5... Bxh8 {[%clk 0:02:57.3]} 6. e3 {[%clk 0:02:57.9]} 6... c5 {[%clk 0:02:54]} 7. Nf3 {[%clk 0:02:57.3]} 7... Nc6 {[%clk 0:02:53.3]} 8. d4 {[%clk 0:02:56.4]} 8... Bg4 {[%clk 0:02:52.1]} 9. Bb5 {[%clk 0:02:54]} 9... cxd4 {[%clk 0:02:48.6]} 10. exd4 {[%clk 0:02:51.1]} 10... Rc8 {[%clk 0:02:48.1]} 11. Be3 {[%clk 0:02:49.7]} 11... e6 {[%clk 0:02:45.9]} 12. Qd2 {[%clk 0:02:42.6]} 12... Bxf3 {[%clk 0:02:45.2]} 13. gxf3 {[%clk 0:02:42.5]} 13... a6 {[%clk 0:02:44.6]} 14. Bxc6+ {[%clk 0:02:41.5]} 14... Rxc6 {[%clk 0:02:44]} 15. Ne2 {[%clk 0:02:38.6]} 15... Ne7 {[%clk 0:02:42.8]} 16. Ng3 {[%clk 0:02:36.9]} 16... Nc8 {[%clk 0:02:40.2]} 17. Ke2 {[%clk 0:02:27.6]} 17... Nd6 {[%clk 0:02:38.5]} 18. Rh1 {[%clk 0:02:26.3]} 18... Bf6 {[%clk 0:02:36.4]} 19. b3 {[%clk 0:02:14.6]} 19... Kd7 {[%clk 0:02:34.2]} 20. Bf4 {[%clk 0:02:12.7]} 20... Nb5 {[%clk 0:02:32.7]} 21. Be5 {[%clk 0:02:09.1]} 21... Bxe5 {[%clk 0:02:31.5]} 22. dxe5 {[%clk 0:02:09]} 22... Rxc2 {[%clk 0:02:31.1]} 0-1

**Comment by daohoangson** [comment]
Were you able to find the root cause for this? @Mercutio1243

**Comment by Mercutio1243** [comment]
Hi daohoanson,

Yes, as mentioned above, the error actually came from using an invalid fen position, which led to the Stockfish chess engine crashing.

So, this is no issue with the package here. But it could be an interesting insight that if you observe a fatal signal 11 error with the package, this could be due to the Stockfish chess engine itself crashing.

Hope this helps!

**Comment by daohoangson** [comment]
Thank you for that information. I think we can keep track of known exit codes to surface better error message for app developers.
