### ISSUE TITLE
Mix-up of characters of two commands in stdin

### ISSUE THREAD

**Issue by Mercutio1243** [ArjanAswal/Stockfish#39]
In rare cases, it seems that a mix up of characters from stdin commands can occur in 1.4.0, when these are transmitted directly one after the other:

Specifically, I had following situation on a Galaxy S21 5G
**Code:**
```
this.stockfishInstance!.stdin = "ucinewgame";
this.stockfishInstance!.stdin = "stop";
```

**Result**
```
Unknown command: 'uinewgame'. Type help for more information. 
Unknown command: 'cstop'. Type help for more information. 
```

I have triple checked, there is no way my part of the code could have given these miss-typed commands. Therefore, I assume they got mixed up in the stockfish package because they were provided in short sequence after each other.

Does this make sense? Has anyone had a similar experience like this one? Do you have any advice how to prevent this? I thought about delaying the next command by a few milliseconds?

**Comment by daohoangson** [comment]
I can imagine this may happen because the commands are sent through a stdin pipe. Which should be very fast since it's happening in memory but apparently if you send commands fast enough, they can get mixed up.

Are you able to reproduce this consistently? We probably need to introduce some sort of mutex to guard the pipes and avoid overlapping commands.

**Comment by daohoangson** [comment]
Yes, adding a delay should help.

Thinking out loud here, introducing a general locking mechanism may be complicated because each command works differently so it's hard to know whether it has finished its output to safely release the lock.

**Comment by Mercutio1243** [comment]
JFYI: I have introduced a delay of 10 milliseconds between commands and have not observed the issue anymore.

It might be worthwhile to think about queueing commands received by stdin and use a similar delay before releasing the same command?

**Comment by daohoangson** [comment]
I think the tricky part is knowing when a command has finished and can be released.

**Comment by Mercutio1243** [comment]
Yeah, I agree, I cannot say how to do this. I was just thinking that having some delay built in might be better than nothing, even if it might not work 100% of all situations? 

Btw, finishing the command here means only that it has been needed to the engine properly, right? Isn't there a way how to assess this from the package view?

**Comment by daohoangson** [comment]
When we ask the Stockfish engine for the next move, it may take a long time to calculate. It makes sense to block new commands during this time. However, if it is the `stop` command, it should go through immediately.

**Comment by Mercutio1243** [comment]
Ok got what you mean but to be honest, I would leave this task to the package user, i.e., timing commands properly depending on the engine output. I for once have set up my own queue manager for that and would not like the package to block commands etc. This is something I would need to manage similarly when working with the engine directly.

However, just that we do not misunderstand each other: The issue I experienced above was a very different one: the characters of my commands got mixed up when they were needed to the engine through your package. This is definitely something I expected the package to prevent, ensuring that each command line to routed through to the engine one after the other without any mix-ups. For this, a simple queue or something else might be helpful?

**Comment by daohoangson** [comment]
I see your points and totally agree with both of them. So instead of blocking incoming command, we should focus on guaranteeing commands are sent to the engine in their intended order. That should be straightforward to do I think.
