### ISSUE TITLE
Example doesn't work on iOS

### ISSUE THREAD

**Issue by daohoangson** [ArjanAswal/Stockfish#5]
Both `go infinite` and `go movetime 3000` crash the app on iOS. I think this may be a threading issue.
They work fine on Android though.

**Comment by ArjanAswal** [comment]
It was working before if I am not wrong?

**Comment by daohoangson** [comment]
It did. I'm looking into it.

**Comment by mono424** [comment]
`go` command still crashes app on ios, any updates to this ? :)

**Comment by ArjanAswal** [comment]
Can you please try the latest version from GitHub and tell me whether its working?

**Comment by mono424** [comment]
Still crashing in iOS Emulator on mac :)

**Comment by daohoangson** [comment]
You may need to do a `flutter clean` then remove the `ios/Pods` directory for the new version to kick in. The previous version writes a bad file into that directory so it needs to be purged.

**Comment by mono424** [comment]
that did the trick thank you ! :)
